In [6]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [12]:
# 4X4 이미지 - 0~7까지 8단계로 구성함
src = np.array([[0, 0, 0, 0],
              [1, 1, 3, 5],
              [6, 1, 1, 3],
              [4, 3, 1, 7]
              ], dtype=np.uint8)

hist = cv2.calcHist(images=[src], channels=[0], mask=None, 
                     histSize=[4], ranges=[0, 8])
print('hist =', hist)

# 높은 값이 할당이 됨
backP = cv2.calcBackProject([src], [0], hist, [0, 8], scale = 1)
print('backP = ', backP)

hist = [[9.]
 [3.]
 [2.]
 [2.]]
backP =  [[9 9 9 9]
 [9 9 3 2]
 [2 9 9 3]
 [2 3 9 2]]


In [19]:
#1
src = cv2.imread('./data/fruits.jpg')
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split(hsv)

#2 히스토그램 -> 역투영
roi = cv2.selectROI(src)
print('roi =', roi) #x, y, w, h

roi_h = h[roi[1]:roi[1]+roi[3], #행
           roi[0]:roi[0]+roi[2]] #열

hist = cv2.calcHist(images=[roi_h], channels=[0], mask=None, 
                    histSize=[64], ranges=[0, 256])
backP = cv2.calcBackProject([h.astype(np.float32)], [0], hist, 
                            [0, 256], scale = 1.0)

#3 threshold를 통해 이진영상으로 만듦
hist = cv2.sort(hist, cv2.SORT_EVERY_COLUMN+cv2.SORT_DESCENDING) 
#내림차순으로 정렬 - why?
#빈도수가 제일 높은 2개만 남기고 없애기!

k = 1
T = hist[k][0] - 1 #threshold - 이진영상으로 만듦
print('T=', T)
ret, dst = cv2.threshold(backP, T, 255, cv2.THRESH_BINARY)

cv2.imshow('dst', dst)
cv2.waitKey()    
cv2.destroyAllWindows()

roi = (394, 168, 89, 63)
T= 1024.0
