In [1]:
import cv2
import numpy as np

### 방법 1. 슬라이싱 이용

In [2]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

(h, w) = img.shape
print(h, w)

(cx, cy) = (h//2, w//2) # 중심을 찾기
print(cy, cx)

roi = img[0:cy, 0:cx]

cv2.imshow('img', img)
cv2.imshow('ROI', roi)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
256 256


In [4]:
#모자이크 영상 만들기
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=src.dtype)

N = 64 # N x N 배열로 만듦
height, width = src.shape # 그레이스케일 영상
h = height // N
w = width // N
for i in range(N):
    for j in range(N):
        y = i*h
        x = j*w
        roi = src[y:y+h, x:x+w]
        val = cv2.mean(roi) #mean - roi영역의 mean값(평균) 반환
        #print(val)
        dst[y:y+h, x:x+w] = val[0] # 그레이스케일 영상
        
cv2.imshow('dst', dst)        
cv2.waitKey()
cv2.destroyAllWindows()

### 방법 2. 마우스를 이용한 ROI 설정

In [6]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)
print('roi =', roi) #x, y, w, h

image = src[roi[1]:roi[1]+roi[3], #행
           roi[0]:roi[0]+roi[2]] #열

cv2.imshow('img', image)        
cv2.waitKey()
cv2.destroyAllWindows()

roi = (231, 332, 264, 180)


In [7]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, False, False)
print('rects =', rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), 255)

cv2.imshow('src', src)        
cv2.waitKey()
cv2.destroyAllWindows()

rects = [[ 89  76 241 290]
 [291 178 182 304]
 [ 40 293 256 156]
 [201 198 230 188]
 [314  23 194 130]]
