In [1]:
import cv2
import numpy as np

In [2]:
src = cv2.imread('./data/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY) #바이너리 이미지로 변환
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('src', src)
cv2.imshow('res', res)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
ret, labels = cv2.connectedComponents(res) #라벨링
print('ret=', ret) #background 1 + component 3 = 4

ret= 4


In [4]:
dst = np.zeros(src.shape, dtype=src.dtype)
for i in range(1, ret) : #분할 영역 표시 - 라벨 별로 다른 색깔이 저장됨
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels == i] = [b, g, r] 
    
cv2.imshow('src', src) #원본
cv2.imshow('res', res) #inverse
cv2.imshow('dst', dst) #라벨링
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(res) #라벨링
print('ret = ', ret) #background 1 + component 3 = 4
print('stats = ', stats) # 바운딩 박스 + area
print('centroids = ', centroids) # 무게 중심의 x, y좌표

ret =  4
stats =  [[     0      0    512    512 222719]
 [   308     86    125    125  12281]
 [   153    145    152    152  18152]
 [   292    338    107    107   8992]]
centroids =  [[247.77339607 258.80937863]
 [370.         148.        ]
 [228.5        220.50534376]
 [345.00077847 390.99477313]]


In [6]:
dst = np.zeros(src.shape, dtype=src.dtype)
for i in range(1, int(ret)): #분할영역 표시
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels == i] = [b, g, r]
    
for i in range(1, int(ret)):
    x, y, width, height, area = stats[i]
    cv2.rectangle(dst, (x,y), (x+width, y+height), (0,0,255), 2) #바운딩박스
    cx, cy = centroids[i]
    cv2.circle(dst, (int(cx), int(cy)), 5, (255,0,0), -1) # 무게중심
    
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()