In [15]:
import cv2
import numpy as np

In [16]:
src = np.zeros(shape=(512, 512, 3), dtype=np.uint8)

#두께 -1? 사각형의 내부를 채움
cv2.rectangle(src, (50, 100), (450, 400), (255, 255, 255), -1)
cv2.rectangle(src, (100, 150), (400, 350), (0, 0, 0), -1)
cv2.rectangle(src, (200, 200), (300, 300), (255, 255, 255), -1)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

In [21]:
mode = cv2.RETR_EXTERNAL
#mode = cv2.RETR_LIST # 안에있는 외곽선까지 검출됨
method = cv2.CHAIN_APPROX_SIMPLE # countour점 4개의 꼭지점만 검출됨
#method = cv2.CHAIN_APPROX_NONE #countour점들이 모두 검출됨*******

#contours - 컨투어 정보를 줌, hierachy 구조 정보까지 줌
contours, hierachy = cv2.findContours(gray, mode, method)
print('type(contours)=', type(contours))
print('type(contours[0])=', type(contours[0]))
print('len(contours)=', len(contours)) #mode가 external이기 때문에 1개만 검출됨
print('contours[0].shape=', contours[0].shape) #contour 포인트 개수 = simple이므로 4개
print('contours[0]=', contours[0])

type(contours)= <class 'tuple'>
type(contours[0])= <class 'numpy.ndarray'>
len(contours)= 3
contours[0].shape= (4, 1, 2)
contours[0]= [[[200 200]]

 [[200 300]]

 [[300 300]]

 [[300 200]]]


In [22]:
cv2.drawContours(src, contours, -1, (255,0,0), 3) #모든 윤곽선

for pt in contours[0][:] : #윤곽선 좌표
    cv2.circle(src, (pt[0][0], pt[0][1]), 5, (0,0,255), -1)
    
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()