In [12]:
import numpy as np
import cv2

In [13]:
src = cv2.imread('./data/components.png')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY) #gray 영상으로 변환
#background가 흰색이기 때문에 INV를 통해 배경을 까맣게 만들어줌
ret, binimg = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

cv2.imshow('src', src)
cv2.imshow('res', binimg)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
#ret - 총 component 갯수 (배경 + 세개의 도형 = 4)
#labels - 라벨링된 이미지
#stats - 바운딩 박스 정보 + area
#centroids - component의 중점
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(binimg)
print('ret', ret)
print('stats', stats)
print('centroids', centroids)

ret 4
stats [[     0      0    712    582 296963]
 [    70     73    339    339  90190]
 [   549     83     96    166  15936]
 [   470    372    128    163  11295]]
centroids [[371.16598027 305.74581345]
 [239.03803082 242.03477104]
 [596.5        165.5       ]
 [533.53563524 453.01761842]]


In [15]:
areas = [s[4] for s in stats[1:]] # 배경을 제외한 component를 저장함
print('area', areas)

idx = np.argmax(areas) # 값이 가장 큰 area 반환
print(f'max label= {idx+1}') 

area [90190, 15936, 11295]
max label= 1


In [17]:
largest_label = 1+idx
mask = (labels == largest_label) #같은 곳을 true로 저장
final_comp = mask*255 #같으면 255, 다르면 0으로 설정
final_comp = cv2.convertScaleAbs(final_comp)

cv2.imshow('src', src)
cv2.imshow('final_comp', final_comp)
cv2.waitKey()
cv2.destroyAllWindows()