In [1]:
import cv2
import numpy as np
import imutils

In [2]:
#템플릿 영상은 gray만!!
src = cv2.imread('./data/circuit.bmp', cv2.IMREAD_GRAYSCALE)
tmp = cv2.imread('./data/circuit_tmp.bmp', cv2.IMREAD_GRAYSCALE) 
dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR) # 출력 표시 영상

R1 = cv2.matchTemplate(src, tmp, cv2.TM_SQDIFF_NORMED) #템플릿 매칭 시작
minVal, _, minLoc, _ = cv2.minMaxLoc(R1) #작을수록 유사하기 때문에 minVal 찾음

print('TM_SQDIFF_NORMED:', minVal, minLoc)
print(R1)

w, h = tmp.shape[:2]
#print(w, h)
cv2. rectangle(dst, minLoc, (minLoc[0]+h, minLoc[1]+w), (255, 0, 0), 2)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

TM_SQDIFF_NORMED: 2.598681589915941e-07 (558, 323)
[[0.7011468  0.697535   0.6957528  ... 0.709112   0.7068629  0.6975021 ]
 [0.6853214  0.67898875 0.67859447 ... 0.6835571  0.68334275 0.67919356]
 [0.67072874 0.664797   0.6678189  ... 0.67577213 0.67726827 0.6765454 ]
 ...
 [0.6772649  0.67611897 0.67739373 ... 0.7184665  0.72168636 0.7213238 ]
 [0.6833954  0.6823485  0.68619555 ... 0.7125044  0.71701884 0.7166337 ]
 [0.6822461  0.6815959  0.68737614 ... 0.7029896  0.7066483  0.7051116 ]]


In [3]:
#템플릿 영상은 gray만!!
src = cv2.imread('./data/circuit_modified.bmp', cv2.IMREAD_GRAYSCALE)
tmp = cv2.imread('./data/circuit_tmp.bmp', cv2.IMREAD_GRAYSCALE) 
dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR) # 출력 표시 영상

R1 = cv2.matchTemplate(src, tmp, cv2.TM_SQDIFF_NORMED) #템플릿 매칭 시작
#R1 = cv2.matchTemplate(src, tmp, cv2.TM_CCORR_NORMED)
#R1 = cv2.matchTemplate(src, tmp, cv2.TM_CCOEFF_NORMED)

minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(R1)
print(R1)
print('TM_SQDIFF_NORMED:', minVal, minLoc) # 작을 수록 유사함
#print('TM_CCORR_NORMED:', maxVal, maxLoc) # 클 수록
#print('TM_CCOEFF_NORMED:', maxVal, maxLoc) # 클 수록

y, x = minLoc[:2]
#y, x = maxLoc[:2]
w, h = tmp.shape[:2]
#print(w, h)
cv2. rectangle(dst, (y, x), (y+h, x+w), (255, 0, 0), 2)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

[[0.48703513 0.48458654 0.4830971  ... 0.48301956 0.4815877  0.47938353]
 [0.48256856 0.47850925 0.4774411  ... 0.4812227  0.4795934  0.47829086]
 [0.4827148  0.4790854  0.47858226 ... 0.47927296 0.47921777 0.47712758]
 ...
 [0.47922915 0.4806652  0.48073003 ... 0.4626947  0.46277082 0.46529713]
 [0.47867963 0.4801647  0.47954175 ... 0.4594709  0.46034846 0.46358985]
 [0.47710156 0.47819293 0.4763688  ... 0.4599569  0.45972398 0.46330684]]
TM_SQDIFF_NORMED: 0.40319156646728516 (558, 323)
